### ISSUE TITLE
Access request

### ISSUE THREAD

**Issue by barrynl** [TNO/pyastbuilder#1]
I do not have permission 😄

**Comment by victorklos** [comment]
Van de settings page:

> Default repository permission
  The TNO organization has their default repository permission set to read. This means that every member of this organization has read access to this repository, regardless of the team and collaborator access specified below.
  To change or remove this organization's default repository permission, contact one of the organization's owners.

Maw: stuur een mail naar Andre Boorsma @aboorsma

**Comment by barrynl** [comment]
Top, bedankt!

**Comment by ferryjagers** [comment]
@barrynl er staat een verzoek voor je uit om collaborator te worden voor deze repo (verstuurd door @victorklos), wanneer je dit verzoek accepteert zal je read+write rechten hebben. Zie https://github.com/TNO/pyAST/settings/collaboration

**Comment by barrynl** [comment]
@ferryjagers @victorklos Stom van mij, je hebt gelijk. Ik had deze email over het hoofd gezien en nu werkt alles naar behoren!

Bedankt!

**Comment by victorklos** [comment]
top, dank je @ferryjagers
